VERSION = '0.1.0'

# Index constants
INDEX_DEFAULT_LOCATION = '~/.cryptostasis/index'
INDEX_VERSION = 2
PASSWORD_SALT_LENGTH = 64
INT_LENGTH = 4
INT_FORMAT = '>I'
MASTER_KEY_HASH_LENGTH = 128
MASTER_KEY_LENGTH = 256
CIPHER_KEY_LENGTH = 128
ENCRYPTED_INDEX_MAC_LENGTH = 128
ENCRYPTION_KEY_LENGTH = 128
TWEAK_LENGTH = 16
MIN_ENCRYPTED_INDEX_LENGTH = 128

# Archive constants
ARCHIVE_VERSION = 1
ARCHIVE_ID_LENGTH = 64
